#pragma once
// OpenColorIO viewing-transform adapter (issue #6, spec section 5/8).
//
// The project ColorPolicy names a working space and a viewer/delivery
// transform against the project's OCIO config. This adapter resolves those
// names and provides:
//
//   - a CPU reference path that applies the named viewing transform with the
//     OpenColorIO CPU processor, and
//   - the GPU-native path: OCIO's own generated Vulkan-GLSL viewing-transform
//     program (OCIO decomposes arbitrary op chains into matrix + 1D/3D LUT
//     texture ops for the GPU) plus the structured LUT data and uniform
//     bytes needed to execute it. Execution itself is the gpu module's job:
//     the program description here is plain data with no GPU objects.
//
// The viewer transform is a downstream viewing operation: it consumes
// scene-linear pixels and never feeds a reusable composition result (spec
// section 8). The GPU program is derived from a single OCIO processor, so
// applying it once to a buffer is exactly one application of the transform.
#include "nemo/core/document/Document.hpp"

#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

#include "nemo/core/evaluation/Image.hpp"

namespace nemo::media {

// Color-management failures always name the offending config or transform
// (repo rule: errors identify the offending relationship).
struct OcioException : std::runtime_error {
    using std::runtime_error::runtime_error;
};

// Which transform of the policy to resolve.
enum class TransformKind { Viewer, Delivery };

// A resolved, executable viewing transform.
//
// The GLSL text is OCIO's generated Vulkan-GLSL program, adapted for compute
// execution: OCIO samples its LUT textures with implicit-LOD `texture()`
// calls, which the Vulkan compute stage cannot express, so this adapter
// rewrites them to `textureLod(..., 0.0)` — equivalent here because OCIO LUT
// textures are single-mip and their coords never vary between pixels.
//
// Bindings consumed by the generated program (set `descriptorSet`):
//   - binding 0: a uniform buffer holding `uniformBytes` (OCIO's uniform
//     block, std140 layout as generated by OCIO).
//   - bindings `textureBindingStart + i`: LUT texture i as a combined image
//     sampler (RGBA float).
// The wrapper entry point `main` is appended by this adapter: it reads
// RGBA float pixels from an SSBO at set `descriptorSet + 1`, binding 0 and
// writes transformed pixels to an SSBO at the same set, binding 1.
struct OcioGpuProgram {
    // OCIO-generated GLSL (Vulkan dialect) + adapter compute wrapper.
    std::string glsl;

    // OCIO uniform-block bytes (empty when the transform has no uniforms).
    std::vector<std::byte> uniformBytes;
    struct Texture {
        std::vector<float> values;
        // 1D LUTs are 2D textures (width x 1); 3D LUTs are width x width x
        // width. One channel-swept RGBA layout as OCIO packs it.
        unsigned width{};
        unsigned height{};
        // 1 for a 1D LUT, 2 for a 2D-packed 1D LUT, 3 for a 3D LUT.
        unsigned dimensions{};
        // Channels in the value stream: 1 (red-channel 1D LUT) or 4
        // (RGBA). 1D LUTs carry OCIO's padded channel layout as-is; 3D LUTs
        // are OCIO RGB triplets expanded to RGBA (alpha 0) because
        // 3-component float images are not sampleable on common desktop
        // drivers.
        unsigned channels{};
        // Descriptor binding index OCIO declared this texture at.
        unsigned binding{};
    };
    std::vector<Texture> textures;

    unsigned descriptorSet{};
    unsigned textureBindingStart{};

    // Result colorspace name the CPU path and GPU program both apply, for
    // diagnostics ("working -> display/view").
    std::string description;
};

// Resolves the config path the same way OCIO applications do: an explicit
// path when given, otherwise the OCIO environment variable. Returns the
// path; throws OcioException naming the missing file/variable.
[[nodiscard]] std::string resolveConfigPath(const std::string& configPath);

// CPU reference path (OpenColorIO CPU processor). Applies the named viewing
// transform to `image`'s RGB in place; alpha passes through and successful
// output is marked DisplayReferred. Throws OcioException when the config
// or any policy name is missing, naming the offending relationship.
void applyViewingTransformCpu(CpuImage& image, const std::string& configPath, const std::string& workingSpace,
                              const std::string& viewerTransform, TransformKind kind = TransformKind::Viewer);

// Convenience overload applying the document's policy against a config.
void applyViewingTransformCpu(CpuImage& image, const std::string& configPath, const ColorPolicy& policy,
                              TransformKind kind = TransformKind::Viewer);

// GPU-native path: builds the executable description of the named viewing
// transform (OCIO's generated Vulkan-GLSL + LUT data + uniform bytes).
// Throws OcioException with the same rules as the CPU path.
[[nodiscard]] OcioGpuProgram buildViewingTransformGpu(const std::string& configPath, const std::string& workingSpace,
                                                      const std::string& viewerTransform,
                                                      TransformKind kind = TransformKind::Viewer);

}  // namespace nemo::media
