#pragma once
// OpenColorIO viewing-transform adapter (issue #6, spec section 5/8).
//
// The project ColorPolicy names a working space and a viewer/delivery
// transform against the project's OCIO config. This adapter resolves those
// names and provides:
//
//   - a CPU reference path that applies the named viewing transform with the
//     OpenColorIO CPU processor, and
//   - the GPU-native path: OCIO's own generated Vulkan-GLSL viewing-transform
//     program (OCIO decomposes arbitrary op chains into matrix + 1D/3D LUT
//     texture ops for the GPU) plus the structured LUT data and uniform
//     bytes needed to execute it. Execution itself is the gpu module's job:
//     the program description here is plain data with no GPU objects.
//
// The viewer transform is a downstream viewing operation: it consumes
// scene-linear pixels and never feeds a reusable composition result (spec
// section 8). The GPU program is derived from a single OCIO processor, so
// applying it once to a buffer is exactly one application of the transform.
#include "nemo/core/document/Document.hpp"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#include "nemo/core/evaluation/Image.hpp"

namespace nemo::media {

// Color-management failures always name the offending config or transform
// (repo rule: errors identify the offending relationship).
struct OcioException : std::runtime_error {
    using std::runtime_error::runtime_error;
};

// Which transform of the policy to resolve.
enum class TransformKind { Viewer, Delivery };

// A resolved, executable viewing transform.
//
// The GLSL text is OCIO's generated Vulkan-GLSL program, adapted for compute
// execution: OCIO samples its LUT textures with implicit-LOD `texture()`
// calls, which the Vulkan compute stage cannot express, so this adapter
// rewrites them to `textureLod(..., 0.0)` — equivalent here because OCIO LUT
// textures are single-mip and their coords never vary between pixels.
//
// Bindings consumed by the generated program (set `descriptorSet`):
//   - binding 0: a uniform buffer holding `uniformBytes` (OCIO's uniform
//     block, std140 layout as generated by OCIO).
//   - bindings `textureBindingStart + i`: LUT texture i as a combined image
//     sampler (RGBA float).
// The wrapper entry point `main` is appended by this adapter: it reads
// RGBA float pixels from an SSBO at set `descriptorSet + 1`, binding 0 and
// writes transformed pixels to an SSBO at the same set, binding 1.
struct OcioGpuProgram {
    // OCIO-generated GLSL (Vulkan dialect) + adapter compute wrapper.
    std::string glsl;

    // OCIO uniform-block bytes (empty when the transform has no uniforms).
    std::vector<std::byte> uniformBytes;
    struct Texture {
        std::vector<float> values;
        // 1D LUTs have height 1; 3D LUTs use width for all three axes.
        unsigned width{};
        unsigned height{};
        // 1 for a 1D LUT, 2 for a 2D-packed 1D LUT, 3 for a 3D LUT.
        unsigned dimensions{};
        // Channels in the GPU value stream: 1 (red) or 4 (RGBA).
        // OCIO's RGB LUTs of every dimension are expanded to RGBA
        // (alpha 0): RGB32F images are not sampleable on common drivers.
        unsigned channels{};
        // Descriptor binding index OCIO declared this texture at.
        unsigned binding{};
    };
    std::vector<Texture> textures;

    unsigned descriptorSet{};
    unsigned textureBindingStart{};

    // The pixel interface the emitted wrapper uses, so a consumer binds the
    // surface the program actually declares (issues #90, #98): the interleaved
    // rgba32f read/write pixel buffers the viewer path owns, or the native
    // packed four-channel image a media frame already is (one read-write
    // rgba32f storage image at the wrapper's binding, transformed in place —
    // no staging buffer, no copy, no second image).
    enum class PixelInterface { Rgba32fBuffers, PackedImage };
    PixelInterface pixelInterface{PixelInterface::Rgba32fBuffers};

    // Result colorspace name the CPU path and GPU program both apply, for
    // diagnostics ("working -> display/view").
    std::string description;
};

// ---------------------------------------------------------------------------
// Input color: encoded source RGB -> working space (issue #81)
// ---------------------------------------------------------------------------
//
// This is the same OCIO adapter applied in the *other* direction. A source's
// samples are ENCODED (camera/display transfer, Rec.709/sRGB or any named
// config space); the composition contract is scene-linear working RGB. The
// Input Transform of a Read is a real config-backed conversion, never a
// viewing transform: it runs before the compositing graph and its result is
// what downstream effects and the Viewer consume.
//
// The adapter owns four things and nothing else: enumerating the active
// config's color spaces (the Input Transform list has no hardcoded names),
// the OCIO content identity that makes reuse keys config-content aware,
// resolving one request's kind/origin, and the retained processor that
// converts encoded RGB into the working space. Core types stay media-free and
// runtime OCIO objects never enter the Document.

// True for the OCIO built-in-config URI form ("ocio://<name>"): a config
// compiled into the OCIO library, not a file on disk. Only this scheme is
// treated specially; any other URI is an ordinary path and is reported
// missing when it does not exist.
[[nodiscard]] bool isBuiltinConfigUri(std::string_view path);

// The owner-approved color policy for a NEW project: the OCIO-embedded,
// version-pinned ACES Studio config, its real scene-linear Rec.709 working
// space, and the ACES 2.0 SDR viewing on sRGB. It is a creation-time default
// only — existing documents keep their authored policy, and an explicit OCIO
// environment override is untouched — and it is applied through the existing
// project owner (ProjectSession), never by changing ColorPolicy's literals
// (legacy documents must keep decoding to their previous meaning).
struct NewProjectColorDefault {
    std::string configUri;  // registered config reference persisted with the project
    ColorPolicy policy;     // working/view/delivery for the new project
};
[[nodiscard]] NewProjectColorDefault newProjectColorDefault();

// Every ACTIVE color space of the resolved config, ordered by name. The
// searchable Input Transform list comes from the project's real config, so
// adding a config space needs no code change. Throws OcioException naming the
// config when it cannot be resolved or loaded.
[[nodiscard]] std::vector<std::string> configInputColorSpaces(const std::string& configPath);

// Opaque content identity of the resolved config and its context
// (`Config::getCacheID`), mixed into a source node's canonical reuse key. A
// config edited in place — same path, different content — therefore cannot
// serve a stale decoded frame or a stale input transform. Empty when the
// request names no config at all (the legacy 'linear' working space).
[[nodiscard]] std::string colorConfigIdentity(const std::string& configPath);

// The project config's file rule for one media path, as plain strings: the
// resolved color-space name and whether it came from the config's DEFAULT rule
// (a configured fallback — reported as a configured default, never as file
// metadata). `found` is false when the config resolves nothing for the path.
struct ConfigFileRule {
    bool found{false};
    std::string colorSpace;
    bool defaultRule{false};
};
[[nodiscard]] ConfigFileRule configFileRuleFor(const std::string& configPath, const std::string& filePath);

// The supported-working-space diagnostic suffix, in one owner: a working-target
// failure must always name the authored working value and the supported target,
// whether the configuration failed to load or failed validation.
[[nodiscard]] std::string workingTargetContext(const std::string& context, const std::string& workingSpace);

// Validates that `workingSpace` really IS scene-linear Rec.709 in this config
// before source samples are converted into it: the name is resolved, must not
// be a data space, must have a linear transfer, and must carry the Rec.709
// primaries. The primaries are proved by evaluating the config's own
// processor and comparing it against the published Rec.709 -> ACES AP0
// matrix, never by trusting the name or a role (in the pinned ACES config the
// `scene_linear` role is ACEScg, not Rec.709). Throws OcioException naming
// the config, the space and the offending relationship.
void requireSceneLinearRec709(const std::string& configPath, const std::string& workingSpace,
                              const std::string& context);

class OcioInputTransform;

// An immutable, retained OCIO configuration snapshot: ONE load per generation,
// reused for the content identity, the working-target validation, the file-rule
// lookup, the canonical space enumeration, the CPU processors and the GPU
// program extraction. A path loader is never called twice for the same
// generation, so new config bytes can never be paired with an old identity, and
// a per-frame consumer (a sequence decode) never re-opens the config.
class OcioConfigSnapshot {
public:
    // Resolves the reference (authored path or 'ocio://' URI, else $OCIO) and
    // loads it once. Throws OcioException naming the missing/broken reference.
    explicit OcioConfigSnapshot(std::string configPath);
    ~OcioConfigSnapshot();
    OcioConfigSnapshot(OcioConfigSnapshot&&) noexcept;
    OcioConfigSnapshot& operator=(OcioConfigSnapshot&&) noexcept;
    OcioConfigSnapshot(const OcioConfigSnapshot&) = delete;
    OcioConfigSnapshot& operator=(const OcioConfigSnapshot&) = delete;

    // Resolved reference this snapshot was loaded from.
    [[nodiscard]] const std::string& reference() const noexcept;
    // Content identity of THIS snapshot: reference + Config::getCacheID of the
    // loaded bytes and the current context.
    [[nodiscard]] const std::string& identity() const noexcept;
    // Every active color space, ordered by name: the searchable Input Transform
    // list of this snapshot.
    [[nodiscard]] std::vector<std::string> colorSpaces() const;
    // Validates that `workingSpace` really is scene-linear Rec.709 in THIS
    // snapshot (by measurement, see the free function below).
    void requireSceneLinearRec709(const std::string& workingSpace, const std::string& context) const;
    // The config's own file rule for a media path. Cheap: an in-memory rule
    // lookup on the retained snapshot, never a reload and never a per-frame
    // cache of resolved frame paths.
    [[nodiscard]] ConfigFileRule fileRuleFor(const std::string& filePath) const;
    // Retained encoded->working conversion for one input space of this snapshot.
    [[nodiscard]] std::shared_ptr<const OcioInputTransform> inputTransform(const std::string& workingSpace,
                                                                           const std::string& inputColorSpace) const;
    // GPU-native description of the same conversion over the native packed
    // four-channel image itself (issue #98): one read-write rgba32f storage
    // image holding the logical raster, converted IN PLACE so a media frame
    // needs no staging copy and no second image. The wrapper reads the packed
    // texel, converts its primaries and stores them back with the texel's own
    // alpha. This is the program a decoded media frame drives; the buffer
    // variant stays the viewer/general surface.
    [[nodiscard]] OcioGpuProgram inputTransformImageGpu(const std::string& workingSpace,
                                                        const std::string& inputColorSpace) const;
    // GPU-native description of the same conversion, extracted from this
    // snapshot (no reload, no path lookup). The emitted wrapper reads and
    // writes one RGBA32F pixel buffer.
    [[nodiscard]] OcioGpuProgram inputTransformGpu(const std::string& workingSpace,
                                                   const std::string& inputColorSpace) const;

private:
    friend class OcioInputTransform;
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

// Retained encoded-RGB -> working conversion for one resolved input color
// space. Construction resolves the names once (and validates the working
// target); `apply` converts a decoded buffer in place: RGB only, alpha
// untouched, no primaries/transfer assumption of its own.
class OcioInputTransform {
public:
    OcioInputTransform(std::string configPath, std::string workingSpace, std::string inputColorSpace);
    // Builds the conversion from a retained snapshot: no reload, and the
    // identity always belongs to the bytes the processor was built from.
    OcioInputTransform(const OcioConfigSnapshot& snapshot, std::string workingSpace, std::string inputColorSpace);
    ~OcioInputTransform();
    OcioInputTransform(OcioInputTransform&&) noexcept;
    OcioInputTransform& operator=(OcioInputTransform&&) noexcept;
    OcioInputTransform(const OcioInputTransform&) = delete;
    OcioInputTransform& operator=(const OcioInputTransform&) = delete;

    // Converts the image's RGB in place from the encoded input space into the
    // working space. Alpha passes through unchanged.
    void apply(CpuImage& image) const;

    [[nodiscard]] const std::string& inputColorSpace() const noexcept;
    // Config reference + config cache id + working space + input space +
    // processor cache id: the exact content identity of this conversion.
    [[nodiscard]] const std::string& identity() const noexcept;

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

// GPU-native input transform for the same conversion, consumed by the
// retained OCIO executor (gpu::GpuViewingTransform) with a scene-linear
// output: hardware-decoded frames are converted on the device without any
// host readback. The buffer variant reads and writes one RGBA32F pixel buffer
// (the viewer/general surface); the image variant converts the native packed
// four-channel image a decoded frame already is, in place (issue #98).
[[nodiscard]] OcioGpuProgram buildInputTransformGpu(const std::string& configPath, const std::string& workingSpace,
                                                    const std::string& inputColorSpace);
[[nodiscard]] OcioGpuProgram buildInputTransformImageGpu(const std::string& configPath, const std::string& workingSpace,
                                                         const std::string& inputColorSpace);

// Resolves the config path the same way OCIO applications do: an explicit
// path when given, otherwise the OCIO environment variable. Returns the
// path; throws OcioException naming the missing file/variable.
[[nodiscard]] std::string resolveConfigPath(const std::string& configPath);

// CPU reference path (OpenColorIO CPU processor). Applies the named viewing
// transform to `image`'s RGB in place; alpha passes through and successful
// output is marked DisplayReferred. Throws OcioException when the config
// or any policy name is missing, naming the offending relationship.
void applyViewingTransformCpu(CpuImage& image, const std::string& configPath, const std::string& workingSpace,
                              const std::string& viewerTransform, TransformKind kind = TransformKind::Viewer);

// Convenience overload applying the document's policy against a config.
void applyViewingTransformCpu(CpuImage& image, const std::string& configPath, const ColorPolicy& policy,
                              TransformKind kind = TransformKind::Viewer);

// GPU-native path: builds the executable description of the named viewing
// transform (OCIO's generated Vulkan-GLSL + LUT data + uniform bytes).
// Throws OcioException with the same rules as the CPU path.
[[nodiscard]] OcioGpuProgram buildViewingTransformGpu(const std::string& configPath, const std::string& workingSpace,
                                                      const std::string& viewerTransform,
                                                      TransformKind kind = TransformKind::Viewer);

}  // namespace nemo::media
